version: 0.2

phases:
  pre_build:
    commands:
      - echo installing dependencies
      - npm install
  build:
    commands:
      - echo Running Tests
      - npm test
      - echo Building Images
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 151296449863.dkr.ecr.us-east-1.amazonaws.com/node:latest
      - docker build -t node-api
      - docker tag node-api:latest 151296449863.dkr.ecr.us-east-1.amazonaws.com/node:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 151296449863.dkr.ecr.us-east-1.amazonaws.com/node:latest
